[

  [
  {
    color: "#4834ad",
    height: 400,
    id: 0,
    image: "",
    inde: 0,
    name: "main",
    opacity: 1,
    setCurentComponent: (a) => setCurentComponent(a),
    type: "ref",
    width: 600,
    z_index: 1
  },
  {
    color: "#FFF700",
    height: 281,
    id: 1,
    image: "",
    left: -84,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.6,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 152,
    type: "circle",
    width: 182,
    z_index: 6
  },
  {
    color: "#FFF700",
    font: 22,
    id: 2,
    left: 215,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "Final Year Project",
    top: 45,
    type: "text",
    weight: 400,
    z_index: 1
  },
  {
    color: "#ffffff",
    font: "30",
    id: 3,
    left: 206,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "DOCUMENT EDITOR PROJECT",
    top: 124,
    type: "text",
    weight: "800",
    z_index: 1
  },
  {
    color: "#FFF700",
    font: "24",
    id: 4,
    left: 209,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "By Swami Prathamesh &",
    top: 248,
    type: "text",
    weight: 400,
    z_index: 1
  },
  {
    color: "#FFF700",
    font: 22,
    id: 5,
    left: 210,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "Khose Abhishek",
    top: 282,
    type: "text",
    weight: 400,
    z_index: 1
  }
]
 [
  {
    color: "#432ead",
    height: 400,
    id: 0,
    image: "",
    inde: 1,
    name: "main",
    opacity: 1,
    setCurentComponent: (a) => setCurentComponent(a),
    type: "ref",
    width: 600,
    z_index: 1
  },
  {
    color: "#FFF700",
    height: 202,
    id: 1,
    image: "",
    left: 291,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.5,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 254,
    type: "circle",
    width: 320,
    z_index: 1
  },
  {
    color: "#FFF700",
    height: 253,
    id: 2,
    image: "",
    left: -16,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.5,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 254,
    type: "circle",
    width: 139,
    z_index: 1
  },
  {
    color: "#b6e1fb",
    font: "50",
    id: 3,
    left: 56,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "WHAT IT CAN DO",
    top: 7,
    type: "text",
    weight: "800",
    z_index: 1
  },
  {
    color: "#FFF700",
    height: 72,
    id: 4,
    image: "",
    left: 6,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 9,
    type: "rect",
    width: 11,
    z_index: 1
  },
  {
    color: "#f0f0f0",
    height: 80,
    id: 5,
    image: "",
    left: 21,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.3,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 7,
    type: "rect",
    width: 576,
    z_index: 1
  },
  {
    color: "#ffc2c2",
    font: "20",
    id: 6,
    left: 257,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "# Can create           # Can edit              # Can design ",
    top: 138,
    type: "text",
    weight: 400,
    z_index: 1
  },
  {
    color: "#c2e4ff",
    font: 22,
    id: 7,
    left: 147,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "# Can create           # Can edit              # Can design ",
    top: 175,
    type: "text",
    weight: 400,
    z_index: 1
  },
  {
    color: "#a0ea85",
    font: 22,
    id: 8,
    left: -4,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "# Can create           # Can edit              # Can design ",
    top: 218,
    type: "text",
    weight: 400,
    z_index: 1
  }
]
 [
  {
    color: "#42e407",
    height: 400,
    id: 0,
    image: "",
    inde: 2,
    name: "main",
    opacity: 1,
    setCurentComponent: (a) => setCurentComponent(a),
    type: "ref",
    width: 600,
    z_index: 1
  },
  {
    color: "#FFF700",
    height: 268,
    id: 1,
    image: "",
    left: -133,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.7,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: -122,
    type: "rect",
    width: 568,
    z_index: 6
  },
  {
    color: "#FFF700",
    height: 79,
    id: 2,
    image: "",
    left: -51,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.8,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 340,
    type: "rect",
    width: 649,
    z_index: 6
  },
  {
    color: "#bbff00",
    height: 116,
    id: 3,
    image: "",
    left: 206,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.7,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 187,
    type: "circle",
    width: 426,
    z_index: 6
  },
  {
    color: "#ffffff",
    font: "30",
    id: 4,
    left: 22,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 0,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "Try every possible combination",
    top: 148,
    type: "text",
    weight: "400",
    z_index: 6
  }
]
 [
  {
    color: "#f0e5e5",
    height: 400,
    id: 0,
    image: "",
    inde: 3,
    name: "main",
    opacity: 1,
    setCurentComponent: (a) => setCurentComponent(a),
    type: "ref",
    width: 600,
    z_index: 1
  },
  {
    color: "#ffa238",
    height: 235,
    id: 1,
    image: "",
    left: -39,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: -5,
    type: "rect",
    width: 242,
    z_index: 1
  },
  {
    color: "#29fbff",
    height: 231,
    id: 2,
    image: "",
    left: 177,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 110,
    type: "rect",
    width: 120,
    z_index: 1
  },
  {
    color: "#ff94eb",
    height: 226,
    id: 3,
    image: "",
    left: 276,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 203,
    type: "rect",
    width: 176,
    z_index: 1
  },
  {
    color: "#69ff29",
    height: 155,
    id: 4,
    image: "",
    left: 188,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: -76,
    type: "rect",
    width: 206,
    z_index: 1
  },
  {
    color: "#ff2929",
    height: 135,
    id: 5,
    image: "",
    left: 363,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.8,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 71,
    type: "rect",
    width: 227,
    z_index: 1
  },
  {
    color: "#FFF700",
    height: 182,
    id: 6,
    image: "",
    left: -69,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 264,
    type: "rect",
    width: 152,
    z_index: 6
  },
  {
    color: "#ce70f0",
    height: 101,
    id: 7,
    image: "",
    left: 480,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: -26,
    type: "rect",
    width: 162,
    z_index: 1
  },
  {
    color: "#1529c1",
    height: 100,
    id: 8,
    image: "",
    left: 93,
    moveElement: moveElement,
    name: "shape",
    opacity: 1,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 359,
    type: "rect",
    width: 100,
    z_index: 6
  },
  {
    color: "#15c188",
    height: 203,
    id: 9,
    image: "",
    left: 495,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.6,
    resizeElement: resizeElement,
    rotate: 37,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 251,
    type: "rect",
    width: 125,
    z_index: 1
  },
  {
    color: "#ffffff",
    height: 246,
    id: 10,
    image: "",
    left: 89,
    moveElement: moveElement,
    name: "shape",
    opacity: 0.6,
    resizeElement: resizeElement,
    rotate: 1,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    top: 68,
    type: "rect",
    width: 444,
    z_index: 1
  },
  {
    color: "#000000",
    font: "60",
    id: 11,
    left: 152,
    moveElement: moveElement,
    name: "text",
    opacity: 1,
    padding: 4,
    resizeElement: resizeElement,
    rotate: 1,
    rotateElement: rotateElement,
    setCurentComponent: (a) => setCurentComponent(a),
    title: "Thank You",
    top: 126,
    type: "text",
    weight: "600",
    z_index: 12
  }
]
]
